### ISSUE TITLE
loss nan problem

### ISSUE THREAD

**Issue by pengc02** [ayaanzhaque/instruct-nerf2nerf#32]
```
│ /root/miniconda3/envs/n2n/lib/python3.8/site-packages/in2n/in2n_pipeline.py:177 in               │
│ get_train_loss_dict                                                                              │
│                                                                                                  │
│   174 │   │   │   │   # write edited image to dataloader                                         │
│   175 │   │   │   │   self.datamanager.image_batch["image"][current_spot] = edited_image.squee   │
│   176 │   │                                                                                      │
│ ❱ 177 │   │   loss_dict = self.model.get_loss_dict(model_outputs, batch, metrics_dict)           │
│   178 │   │                                                                                      │
│   179 │   │   return model_outputs, loss_dict, metrics_dict                                      │
│   180                                                                                            │
│                                                                                                  │
│ /root/miniconda3/envs/n2n/lib/python3.8/site-packages/in2n/in2n.py:69 in get_loss_dict           │
│                                                                                                  │
│   66 │   │   if self.config.use_lpips:                                                           │
│   67 │   │   │   out_patches = (outputs["rgb"].view(-1, self.config.patch_size,self.config.pa    │
│   68 │   │   │   gt_patches = (image.view(-1, self.config.patch_size,self.config.patch_size,     │
│ ❱ 69 │   │   │   loss_dict["lpips_loss"] = self.config.lpips_loss_mult * self.lpips(out_patch    │
│   70 │   │                                                                                       │
│   71 │   │   if self.training:                                                                   │
│   72 │   │   │   loss_dict["interlevel_loss"] = self.config.interlevel_loss_mult * interlevel    │
│                                                                                                  │
│ /root/miniconda3/envs/n2n/lib/python3.8/site-packages/torch/nn/modules/module.py:1194 in         │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /root/miniconda3/envs/n2n/lib/python3.8/site-packages/torchmetrics/metric.py:236 in forward      │
│                                                                                                  │
│   233 │   │   if self.full_state_update or self.full_state_update is None or self.dist_sync_on   │
│   234 │   │   │   self._forward_cache = self._forward_full_state_update(*args, **kwargs)         │
│   235 │   │   else:                                                                              │
│ ❱ 236 │   │   │   self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)       │
│   237 │   │                                                                                      │
│   238 │   │   return self._forward_cache                                                         │
│   239                                                                                            │
│                                                                                                  │
│ /root/miniconda3/envs/n2n/lib/python3.8/site-packages/torchmetrics/metric.py:302 in              │
│ _forward_reduce_state_update                                                                     │
│                                                                                                  │
│   299 │   │   self._enable_grad = True  # allow grads for batch computation                      │
│   300 │   │                                                                                      │
│   301 │   │   # calculate batch state and compute batch value                                    │
│ ❱ 302 │   │   self.update(*args, **kwargs)                                                       │
│   303 │   │   batch_val = self.compute()                                                         │
│   304 │   │                                                                                      │
│   305 │   │   # reduce batch and global state                                                    │
│                                                                                                  │
│ /root/miniconda3/envs/n2n/lib/python3.8/site-packages/torchmetrics/metric.py:390 in wrapped_func │
│                                                                                                  │
│   387 │   │   │   self._update_count += 1                                                        │
│   388 │   │   │   with torch.set_grad_enabled(self._enable_grad):                                │
│   389 │   │   │   │   try:                                                                       │
│ ❱ 390 │   │   │   │   │   update(*args, **kwargs)                                                │
│   391 │   │   │   │   except RuntimeError as err:                                                │
│   392 │   │   │   │   │   if "Expected all tensors to be on" in str(err):                        │
│   393 │   │   │   │   │   │   raise RuntimeError(                                                │
│                                                                                                  │
│ /root/miniconda3/envs/n2n/lib/python3.8/site-packages/torchmetrics/image/lpip.py:149 in update   │
│                                                                                                  │
│   146 │   def update(self, img1: Tensor, img2: Tensor) -> None:  # type: ignore                  │
│   147 │   │   """Update internal states with lpips score."""                                     │
│   148 │   │   if not (_valid_img(img1, self.normalize) and _valid_img(img2, self.normalize)):    │
│ ❱ 149 │   │   │   raise ValueError(                                                              │
│   150 │   │   │   │   "Expected both input arguments to be normalized tensors with shape [N, 3   │
│   151 │   │   │   │   f" Got input with shape {img1.shape} and {img2.shape} and values in rang   │
│   152 │   │   │   │   f" {[img1.min(), img1.max()]} and {[img2.min(), img2.max()]} when all va   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Expected both input arguments to be normalized tensors with shape [N, 3, H, W]. Got input with shape torch.Size([16, 3, 32, 32]) and torch.Size([16, 3, 32, 32]) and values in range [tensor(nan, device='cuda:0', 
grad_fn=<MinBackward1>), tensor(nan, device='cuda:0', grad_fn=<MaxBackward1>)] and [tensor(-1., device='cuda:0'), tensor(1., device='cuda:0')] when all values are expected to be in the [-1, 1] range.
terminate called without an active exception
```
i met the problem randomly when training on my own data, it seems that the loss went nan, why does this happen,how can i solve this.

**Comment by ayaanzhaque** [comment]
Hi, thanks for bringing this to my attention. I believe I'll just have to do a torch.nan_to_num in the code so this is fixed. I will add that soon and then let you know when it is updated!

**Comment by ayaanzhaque** [comment]
DId you ever run into this issue again? It seems that the patches have nan values, which suggests your training collapsed. Did you view it in the viewer? Did it turn all black? How many iterations did you train for?

**Comment by pengc02** [comment]
> DId you ever run into this issue again? It seems that the patches have nan values, which suggests your training collapsed. Did you view it in the viewer? Did it turn all black? How many iterations did you train for?

I think the problem was caused by having too many images in my dataset, probably over 100. When I reduced it to 70-80 images, the issue was resolved. Thanks for your reply.

**Comment by ayaanzhaque** [comment]
I see, glad to hear that its fixed. Maybe it was just some data-processing issue, I've trained In2n with datasets up to 300.

**Comment by yonghoonkwon** [comment]
What is the problem if the rendering result image turns black during learning?

**Comment by yonghoonkwon** [comment]
> I see, glad to hear that its fixed. Maybe it was just some data-processing issue, I've trained In2n with datasets up to 300.


What is the problem if the rendering result image turns black during training?

**Comment by mfischer-ucl** [comment]
I'm having the same issue: 
```

Step (% Done)       Train Iter (time)    ETA (time)           Train Rays / Sec                       
-----------------------------------------------------------------------------------                  
30000 (200.00%)     2 s, 998.102 ms      11 h, 30 m, 29 s     5.46 K                                 
---------------------------------------------------------------------------------------------------- 
Viewer at: https://viewer.nerf.studio/versions/23-05-15-1/?websocket_url=ws://localhost:49263        
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 1.5090              
Traceback (most recent call last):
  File "/home/anaconda3/envs/in2n/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/research/instructnerf2nerf_data/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/research/instructnerf2nerf_data/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/research/instructnerf2nerf_data/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/research/instructnerf2nerf_data/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/home/research/instructnerf2nerf_data/nerfstudio/nerfstudio/engine/trainer.py", line 252, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/home/research/instructnerf2nerf_data/nerfstudio/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/home/research/instructnerf2nerf_data/nerfstudio/nerfstudio/engine/trainer.py", line 472, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/home/anaconda3/envs/in2n/lib/python3.8/site-packages/in2n/in2n_pipeline.py", line 186, in get_train_loss_dict
    loss_dict = self.model.get_loss_dict(model_outputs, batch, metrics_dict)
  File "/home/anaconda3/envs/in2n/lib/python3.8/site-packages/in2n/in2n.py", line 69, in get_loss_dict
    loss_dict["lpips_loss"] = self.config.lpips_loss_mult * self.lpips(out_patches, gt_patches)
  File "/home/anaconda3/envs/in2n/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anaconda3/envs/in2n/lib/python3.8/site-packages/torchmetrics/metric.py", line 298, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/home/anaconda3/envs/in2n/lib/python3.8/site-packages/torchmetrics/metric.py", line 367, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/home/anaconda3/envs/in2n/lib/python3.8/site-packages/torchmetrics/metric.py", line 457, in wrapped_func
    update(*args, **kwargs)
  File "/home/anaconda3/envs/in2n/lib/python3.8/site-packages/torchmetrics/image/lpip.py", line 139, in update
    loss, total = _lpips_update(img1, img2, net=self.net, normalize=self.normalize)
  File "/home/anaconda3/envs/in2n/lib/python3.8/site-packages/torchmetrics/functional/image/lpips.py", line 360, in _lpips_update
    raise ValueError(
ValueError: Expected both input arguments to be normalized tensors with shape [N, 3, H, W]. Got input with shape torch.Size([16, 3, 32, 32]) and torch.Size([16, 3, 32, 32]) and values in range [tensor(nan, device='cuda:0', grad_fn=<MinBackward1>), tensor(nan, device='cuda:0', grad_fn=<MaxBackward1>)] and [tensor(-0.9922, device='cuda:0'), tensor(0.9922, device='cuda:0')] when all values are expected to be in the [-1, 1] range.

```

training with a fresh install, a new nerfstudio install (cloned from github, latest version), a pretrained nerfacto model and 100 png images. ubuntu 20.04, RTX3090 series, cuda 11.8

**Comment by ayaanzhaque** [comment]
This is pretty surprising. Can you try using fewer images? You could also turn off the LPIPS loss in the config. But this seems to be more of a data issue, I'd print the images and renders to make sure they are good.

**Comment by mfischer-ucl** [comment]
I triple-checked the images, they're all good, but I'm suspecting it's got to do with the transforms.json we were using. I switched to the MipNeRF360 dataset, it seems to be working fine now!
