### ISSUE TITLE
Fresh install error

### ISSUE THREAD

**Issue by Iliceth** [ayaanzhaque/instruct-nerf2nerf#72]
Hi all, I did a fresh install today, everything seemed to go fine, but when I checked the install with `ns-train -h`, this was the result:

```
(instruct_nerf2nerf_v2) C:\Users\Andy\Documents\instruct-nerf2nerf>ns-train -h
C:\Users\Andy\Anaconda3\envs\instruct_nerf2nerf_v2\lib\site-packages\nerfstudio\utils\misc.py:184: RuntimeWarning: Windows does not yet support torch.compile and the performance will be affected.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Andy\Anaconda3\envs\instruct_nerf2nerf_v2\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Andy\Anaconda3\envs\instruct_nerf2nerf_v2\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Andy\Anaconda3\envs\instruct_nerf2nerf_v2\Scripts\ns-train.exe\__main__.py", line 4, in <module>
  File "C:\Users\Andy\Anaconda3\envs\instruct_nerf2nerf_v2\lib\site-packages\nerfstudio\scripts\train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "C:\Users\Andy\Anaconda3\envs\instruct_nerf2nerf_v2\lib\site-packages\nerfstudio\configs\method_configs.py", line 607, in <module>
    all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_methods())
  File "C:\Users\Andy\Anaconda3\envs\instruct_nerf2nerf_v2\lib\site-packages\nerfstudio\plugins\registry.py", line 43, in discover_methods
    spec = discovered_entry_points[name].load()
  File "C:\Users\Andy\Anaconda3\envs\instruct_nerf2nerf_v2\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 208, in load
    module = import_module(match.group('module'))
  File "C:\Users\Andy\Anaconda3\envs\instruct_nerf2nerf_v2\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Andy\Documents\instruct-nerf2nerf\in2n\in2n_config.py", line 47, in <module>
    model=InstructNeRF2NeRFModelConfig(
TypeError: __init__() got an unexpected keyword argument 'camera_optimizer'
```

**Comment by Iliceth** [comment]
After also installing nerfstudio as a whole as specified on their website, instead of stopping after only the prerequisites, requested in your instructions, it worked.

**Comment by ttaa9** [comment]
I also get this error after trying to run the new version from #60

**Comment by lsongx** [comment]
@ttaa9 try install nerfstudio again with
```
git clone https://github.com/nerfstudio-project/nerfstudio.git
cd nerfstudio
pip install --upgrade pip setuptools
pip install -e .
```

**Comment by jhq1234** [comment]
I got this error too when I installed nerfstudio and then got in2n.

**Comment by lsongx** [comment]
@jhq1234 This error is due to not using the latest nerfstudio

```
git clone https://github.com/nerfstudio-project/nerfstudio.git
cd nerfstudio
pip install --upgrade pip setuptools
pip install -e .
```

**Comment by jhq1234** [comment]
@lsongx It works for me! Thanks!
