### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'camera_optimizer'

### ISSUE THREAD

**Issue by AdvancedHe** [ayaanzhaque/instruct-nerf2nerf#85]
Hi, when I use command:`ns-train -h`, it appeared:
```
Traceback (most recent call last):
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/configs/method_configs.py", line 607, in <module>
    all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_methods())
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/plugins/registry.py", line 43, in discover_methods
    spec = discovered_entry_points[name].load()
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
    module = import_module(match.group('module'))
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/in2n/in2n_config.py", line 47, in <module>
    model=InstructNeRF2NeRFModelConfig(
TypeError: __init__() got an unexpected keyword argument 'camera_optimizer'
```

How to solve this problem?

**Comment by lsongx** [comment]
Seems to be the same as https://github.com/ayaanzhaque/instruct-nerf2nerf/issues/72


@AdvancedHe  try install nerfstudio again with
```
git clone https://github.com/nerfstudio-project/nerfstudio.git
cd nerfstudio
pip install --upgrade pip setuptools
pip install -e .
```

**Comment by AdvancedHe** [comment]
Thanks, it helps me solve this problem.
