### ISSUE TITLE
OSError: [Errno 122] Disk quota exceeded

### ISSUE THREAD

**Issue by AdvancedHe** [ayaanzhaque/instruct-nerf2nerf#86]
Hi, when I use: `ns-train in2n-small --data data/bear --load-dir outputs/bear/nerfacto/2023-12-17_230904/nerfstudio_models --pipeline.prompt "Turn the bear into a polar bear" --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 1.5`, it appeared:

`diffusion_pytorch_model.safetensors:   1%|▊                                                                                         | 31.5M/3.44G [00:04<08:07, 6.99MB/s]
diffusion_pytorch_model.safetensors:  13%|███████████▍                                                                               | 41.9M/335M [00:04<00:32, 8.95MB/s]
model.safetensors:   9%|█████████▎                                                                                                   | 41.9M/492M [00:04<00:51, 8.79MB/s]
Fetching 13 files:  31%|███████████████████████████████████                                                                               | 4/13 [00:05<00:11,  1.33s/it]
Traceback (most recent call last):
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1457, in hf_hub_download
    http_get(
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 527, in http_get
    temp_file.write(chunk)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/tempfile.py", line 473, in func_wrapper
    return func(*args, **kwargs)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/group/ossmodelzoo/hecui/codelib/instruct-nerf2nerf/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/group/ossmodelzoo/hecui/codelib/instruct-nerf2nerf/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/group/ossmodelzoo/hecui/codelib/instruct-nerf2nerf/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/group/ossmodelzoo/hecui/codelib/instruct-nerf2nerf/nerfstudio/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/group/ossmodelzoo/hecui/codelib/instruct-nerf2nerf/nerfstudio/nerfstudio/engine/trainer.py", line 147, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/group/ossmodelzoo/hecui/codelib/instruct-nerf2nerf/nerfstudio/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/group/ossmodelzoo/hecui/codelib/instruct-nerf2nerf/in2n/in2n_pipeline.py", line 84, in __init__
    self.ip2p = InstructPix2Pix(self.ip2p_device, ip2p_use_full_precision=self.config.ip2p_use_full_precision)
  File "/group/ossmodelzoo/hecui/codelib/instruct-nerf2nerf/in2n/ip2p.py", line 71, in __init__
    pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(IP2P_SOURCE, torch_dtype=torch.float16, safety_checker=None)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1090, in from_pretrained
    cached_folder = cls.download(
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1856, in download
    cached_folder = snapshot_download(
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 308, in snapshot_download
    thread_map(
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 283, in _inner_hf_hub_download
    return hf_hub_download(
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1457, in hf_hub_download
    http_get(
  File "/group/ossmodelzoo/hecui/PythonIDES/envs/nerfstudio/lib/python3.8/tempfile.py", line 491, in __exit__
    result = self.file.__exit__(exc, value, tb)
OSError: [Errno 122] Disk quota exceeded
`
What should I do to solve this problem?
Thanks!

**Comment by ayaanzhaque** [comment]
It looks like your disk ran out of space when trying to download the InstructPix2Pix model.

**Comment by AdvancedHe** [comment]
> It looks like your disk ran out of space when trying to download the InstructPix2Pix model.

Yes, I modified the path of huggingface model, then it worked!
Thanks a lot.
