### ISSUE TITLE
Unable to connect to instruct-pix2pix

### ISSUE THREAD

**Issue by jly0810** [ayaanzhaque/instruct-nerf2nerf#98]
During the editing training phase, I encountered the following problem. I tried using VPN but it didn't work. How can I solve it?
Couldn't connect to the Hub: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/timbrooks/instruct-pix2pix (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1135)')))"), '(Request ID: 47f0e2b9-5e1c-47b7-b3a1-2ea343018d99)').
Will try to load from local cache.
Traceback (most recent call last):
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\urllib3\connectionpool.py", line 712, in urlopen
    self._prepare_proxy(conn)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\urllib3\connectionpool.py", line 1012, in _prepare_proxy
    conn.connect()
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1135)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/timbrooks/instruct-pix2pix (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1135)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1205, in download
    info = model_info(pretrained_model_name, token=token, revision=revision)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\huggingface_hub\hf_api.py", line 2227, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\huggingface_hub\utils\_http.py", line 68, in send
    return super().send(request, *args, **kwargs)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/timbrooks/instruct-pix2pix (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1135)')))"), '(Request ID: 47f0e2b9-5e1c-47b7-b3a1-2ea343018d99)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "F:\project\AIGC\Editor_Project\Instruct-NeRF2NeRF\nerfstudio\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "F:\project\AIGC\Editor_Project\Instruct-NeRF2NeRF\nerfstudio\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "F:\project\AIGC\Editor_Project\Instruct-NeRF2NeRF\nerfstudio\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "F:\project\AIGC\Editor_Project\Instruct-NeRF2NeRF\nerfstudio\nerfstudio\scripts\train.py", line 99, in train_loop
    trainer.setup()
  File "F:\project\AIGC\Editor_Project\Instruct-NeRF2NeRF\nerfstudio\nerfstudio\engine\trainer.py", line 149, in setup
    self.pipeline = self.config.pipeline.setup(
  File "F:\project\AIGC\Editor_Project\Instruct-NeRF2NeRF\nerfstudio\nerfstudio\configs\base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "F:\project\AIGC\Editor_Project\Instruct-NeRF2NeRF\Instruct-NeRF2NeRF\in2n\in2n_pipeline.py", line 84, in __init__
    self.ip2p = InstructPix2Pix(self.ip2p_device, ip2p_use_full_precision=self.config.ip2p_use_full_precision)
  File "F:\project\AIGC\Editor_Project\Instruct-NeRF2NeRF\Instruct-NeRF2NeRF\in2n\ip2p.py", line 71, in __init__
    pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(IP2P_SOURCE, torch_dtype=torch.float16, safety_checker=None)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 671, in from_pretrained
    cached_folder = cls.download(
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Load_File\Anaconda3\envs\nerfstudio\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1454, in download
    raise EnvironmentError(
OSError: Cannot load model timbrooks/instruct-pix2pix: model is not cached locally and an error occurred while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.

I also tried the ping command, but couldn't connect.
ping huggingface.co
正在 Ping huggingface.co [199.59.149.230] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。

Do you have any other solutions？

**Comment by lisusuba** [comment]
请问您解决了吗？
